// Service Worker Boilerplate Generated by CodeSmith.in
// Generation Date: 2026-01-09T17:57:25.165Z

const CACHE_VERSION = 'v1.0.0';
const CACHE_NAME = 'app-cache-' + CACHE_VERSION;
const OFFLINE_FALLBACK = 'offline.html';

const PRECACHE_ASSETS = [
  'index.html',
  'style.css',
  'offline.html',
  '/links/',
  '/canvas/',
  '/imagetolua/',
  '/images/'
];

// Installation: Pre-cache critical resources
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(PRECACHE_ASSETS.concat([OFFLINE_FALLBACK]));
    })
  );
});

// Activation: Clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});

// Fetch handling with different strategies
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.pathname.startsWith('/images/**')) {
          // Stale While Revalidate strategy for images/**
          event.respondWith(
            caches.match(event.request).then((response) => {
              const fetchPromise = fetch(event.request).then((networkResponse) => {
                caches.open(CACHE_NAME).then((cache) => {
                  cache.put(event.request, networkResponse.clone());
                });
                return networkResponse;
              });
              return response || fetchPromise;
            })
          )
  }

  // Offline fallback
  event.respondWith(
    fetch(event.request).catch(() => {
      return caches.match('offline.html');
    })
  );
});